Resp_GetReferenceRates_200_application_json:
  type: object
  required:
  - meta
  - data
  - links
  properties:
    meta:
      $ref: ./MetaPagination.yaml#/MetaPagination
    data:
      type: array
      items:
        type: object
        properties:
          date:
            type: string
            format: date
            description: Observation date.
          code:
            type: string
            description: Reference rate code.
          currency:
            type: string
            description: Currency of the rate.
          rate_type:
            type: string
            description: Type of rate.
          rate:
            type: number
            description: Rate value.
          source:
            type: string
            description: Data source.
          source_series_id:
            type: string
            description: Source series identifier.
    links:
      $ref: ./Links.yaml#/Links
  additionalProperties: false
