Resp_GetIntradayHistoricalData_200_application_json:
  type: array
  items:
    type: object
    properties:
      timestamp:
        type: integer
      gmtoffset:
        type: integer
      datetime:
        type: string
        format: date-time
      open:
        type: number
      high:
        type: number
      low:
        type: number
      close:
        type: number
      volume:
        type:
        - integer
        - 'null'
